version: "3.8"

services:

  zookeeper:
    image: zookeeper:3.6
    ports:
      - 2181:2181
    networks:
      - kafkanet

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    networks:
      - kafkanet
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_CREATE_TOPICS: "mulog:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://localhost:9092, INSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT,INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://:9094,OUTSIDE://:9092


networks:
  kafkanet:
    name: kafka-network