version: '3'

services:
  elasticsearch:
    #image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
  kibana:
    #image: docker.elastic.co/kibana/kibana:6.7.0
    #image: docker.elastic.co/kibana/kibana:7.4.1
    #image: docker.elastic.co/kibana/kibana:7.8.0
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - "9000:5601"
